const msg = {
    try_smaller_mtu: '尝试更小的 MTU: ',
    burning: '正在烧录 ',
    fallback_mtu: '回退到 MTU 最小值(23)',
    error_retry: '出现错误，重试...',
    enable_fota: "使能 FOTA...",
    failed_fota: "无法使能 FOTA",
    err_dev_not_ready: '错误: 设备未就绪',
    err_nothing_to_up: '错误: 不需要更新',
    fota_complete: "FOTA 烧录完成，重启设备...",
    exception: '异常: ',
    scaning: '扫描 BLE 设备 ...',
    connecting: '正在连接 ...',
    cannot_conn: '无法连接到所选择的设备',
    dev_disc: '设备连接已断开',
    discover_fota: '正在发现 INGCHIPS FOTA 服务 ...',
    query_ver: '正在查询版本信息 ...',
    sel_dev: '选择一个 BLE 设备',
    sec_fota_confirm: '请确认设备上具备附属 FOTA 程序，然后点击 Yes/确认',
    exchange_keys: '交换密钥',
    mtu_too_small: '对于安全 FOTA，当前 MTU 太小了'
}